import * as React from "react";
export const IconMuk = React.createElement("g", null,
    React.createElement("path", { d: "M 0,-3.5700404e-5 20,19.999964 l -20,20 z", style: { "color": "#000000", "clipRule": "nonzero", "display": "inline", "overflow": "visible", "visibility": "visible", "opacity": 1, "isolation": "auto", "mixBlendMode": "normal", "colorInterpolation": "sRGB", "colorInterpolationFilters": "linearRGB", "solidColor": "#000000", "solidOpacity": 1, "fill": "#6858e8", "fillOpacity": 1, "fillRule": "nonzero", "stroke": "none", "strokeWidth": 5, "strokeLinecap": "round", "strokeLinejoin": "miter", "strokeMiterlimit": 4, "strokeDasharray": "5, 15", "strokeDashoffset": 0, "strokeOpacity": 1, "colorRendering": "auto", "imageRendering": "auto", "shapeRendering": "auto", "textRendering": "auto", "enableBackground": "accumulate" }, id: "path3" }),
    "  ",
    React.createElement("path", { d: "m 0,39.999964 20,-20 20,20 z", style: { "color": "#000000", "clipRule": "nonzero", "display": "inline", "overflow": "visible", "visibility": "visible", "opacity": 1, "isolation": "auto", "mixBlendMode": "normal", "colorInterpolation": "sRGB", "colorInterpolationFilters": "linearRGB", "solidColor": "#000000", "solidOpacity": 1, "fill": "#29235c", "fillOpacity": 1, "fillRule": "nonzero", "stroke": "none", "strokeWidth": 5, "strokeLinecap": "round", "strokeLinejoin": "miter", "strokeMiterlimit": 4, "strokeDasharray": "5, 15", "strokeDashoffset": 0, "strokeOpacity": 1, "colorRendering": "auto", "imageRendering": "auto", "shapeRendering": "auto", "textRendering": "auto", "enableBackground": "accumulate" }, id: "path5" }),
    "  ",
    React.createElement("path", { d: "m 40,39.999964 -20,-20 L 40,-3.5700404e-5 Z", style: { "color": "#000000", "clipRule": "nonzero", "display": "inline", "overflow": "visible", "visibility": "visible", "opacity": 1, "isolation": "auto", "mixBlendMode": "normal", "colorInterpolation": "sRGB", "colorInterpolationFilters": "linearRGB", "solidColor": "#000000", "solidOpacity": 1, "fill": "#2d95d3", "fillOpacity": 1, "fillRule": "nonzero", "stroke": "none", "strokeWidth": 5, "strokeLinecap": "round", "strokeLinejoin": "miter", "strokeMiterlimit": 4, "strokeDasharray": "5, 15", "strokeDashoffset": 0, "strokeOpacity": 1, "colorRendering": "auto", "imageRendering": "auto", "shapeRendering": "auto", "textRendering": "auto", "enableBackground": "accumulate" }, id: "path7" }),
    "  ",
    React.createElement("path", { d: "m 40,-3.6e-5 -20,20 -19.99999985,-20 z", style: { "color": "#000000", "clipRule": "nonzero", "display": "inline", "overflow": "visible", "visibility": "visible", "opacity": 1, "isolation": "auto", "mixBlendMode": "normal", "colorInterpolation": "sRGB", "colorInterpolationFilters": "linearRGB", "solidColor": "#000000", "solidOpacity": 1, "fill": "#ffffff", "fillOpacity": 1, "fillRule": "nonzero", "stroke": "none", "strokeWidth": 5, "strokeLinecap": "round", "strokeLinejoin": "miter", "strokeMiterlimit": 4, "strokeDasharray": "5, 15", "strokeDashoffset": 0, "strokeOpacity": 1, "colorRendering": "auto", "imageRendering": "auto", "shapeRendering": "auto", "textRendering": "auto", "enableBackground": "accumulate" }, id: "path7-3" }));
//# sourceMappingURL=IconMuk.js.map